# Generated by Django 3.2 on 2022-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220514_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
